wavelink/node.py

As identifier is already displayed, I see no reason to display host publicly in the repr

Remove host from node repr

---

wavelink/__init__.py

As this package is released on PyPI already as full versions, not alpha pre-releases, there's no reason to continue keeping this version tag in the `__init__.py`, so this PR removes it.

Remove the alpha prerelease tag due to match published pkg.

---

.github/workflows/publish.yml

This adds the the Github Action workflow for publishing the package to PyPI automatically when a new Github Release is created.

Publish to PyPI when a Github release is created.

---

wavelink/client.py

Added an optional kwarg `node_id`.
Breaking change: positional arg `cls`  is now a kwarg.
`node_id` allows users to specify which node a new player should be created under. If the node cannot be found an error is raised.
Players that already exist are not affected by this kwarg.
`cls` is now a kwarg. This is a breaking change.

Design changes to client.get_player

---

requirements.txt

This is to fix issue #38 
We are currently testing this with a Discord after updating aiohttp to match Discord.py Version: 1.3.0a2146+g4ef0fb0 with no errors.

Update Requirements.txt for Discord.py 1.3.0a

---

docs/wavelink.rst

This pull request fixes the example present in the docs by making the ``Music`` cog actually subclass ``commands.Cog`` as it's required by the current stable version of discord.py.

Fix outdated docs example

---

wavelink/player.py

Local files have the `identifier` attribute set to their file path, as such the `thumb` attribute was set.
This is fixed by ensuring the `ytid` attribute is a valid YouTube ID

Fix issue with Track.thumb attribute when playing local file.

---

wavelink/websocket.py

Wavelink tries to access the 'threshold' key but it is 'thresholdMs'.

Fix TrackStuck 'threshold' KeyError.

---

wavelink/__init__.py
wavelink/client.py
wavelink/node.py
wavelink/websocket.py

This stabilizes connection to Nodes hosted on a VPS with a router or any such intermediate process that closes the connection if it remains idle.
Which puts the bot in a "reconnection" loop, this PR fixes that.
```py
async def start_nodes(self) -> None:
"""Connect and intiate nodes."""
nodes = {'MAIN': {'host': 'lavaserver.badhost.com',
'port': 80,
'rest_uri': 'http://lavaserver.badhost.com',
'password': "verytrivialpassword",
'identifier': 'MAIN',
'region': 'us_central',
'heartbeat': 40.0 # ping the server every 40s 
}}                # to prevent router from terminating connection
for n in nodes.values():
await self.bot.wavelink.initiate_node(**n)
```
The change introduced is not breaking since heartbeat parameter is Optional[].
The Docstring for `initiate_node` method has been updated.

Add Optional argument 'heartbeat' to node and initiate_node.

---

wavelink/player.py

Quick fix for the 'ShardInfo' object has no attribute 'ws' error when using discord.py 1.4.0a

fix for d.py 1.4.0a

---

wavelink/client.py
wavelink/node.py
wavelink/websocket.py

This adds support to do things like `bot.wavelink.set_serializer(ujson.dumps)` and pretty much any other JSON encoder that dumps to strings or bytes. I did not know a better way to do this other than 3 attributes on all classes to make sure they are being created correctly for any future cases.
I left a note regarding sending bytes, as it would be technically more efficient, yet Lavalink rejects binary traffic for now. Might want to request that in upstream.
I've tested the basic idea of dumping and then using `send_str` in production with orjson and the `send_json` from aiohttp pretty much dumps it and sends it then anyways, so there is no overhead created here, yet using a kwarg to the `send_json` would not allow JSON encoders that return bytes, so I decided for this way.

Support custom JSON encoders

---

wavelink/player.py

[According to youtube API doc](https://developers.google.com/youtube/v3/docs/thumbnails#properties) not all video have a maxres version of their thumbnail.
Example:
https://img.youtube.com/vi/cwQgjq0mCdE/hqdefault.jpg Work but not 
https://img.youtube.com/vi/cwQgjq0mCdE/maxresdefault.jpg

Use hqdefault instead of maxresdefault

---

examples/advanced.py

This PR fixes some useless math in the `advanced` example

Fix useless math in advanced example.

---

examples/advanced.py

There is a typo in the description of the advanced example.

Fix typo in advanced example

---

wavelink/websocket.py

from [this commit](https://github.com/Pycord-Development/Pycord.Wavelink/commit/e29b23d1955f8b1ac28642c9be14181c8a74a1f2) on the Pycord Wavelink Fork

fix `Player.is_playing` always returning True

---

wavelink/player.py

This adds a `**kwargs` consumption parameter to `Player.connect` and the subsequent call to method internals.
I opted for `**kwargs` both for backwards compatibility and inter-library usage.
The "fix" currently is to provide both `self_mute` and `self_deaf` kwargs to the method call. Please let me know if you'd like a better method.

Update player.py to work with dpy2.0

---

wavelink/tracks.py

This adds an own __str__ function for the YouTubePlaylist as it has no title, so print(YouTubePlaylist) doesn't raise an AttributeError.

Add own __str__ for YouTubePlaylist

---

wavelink/player.py

There doesn't appear to be any special handling for `None` here, so this is actually sent straight to Lavalink as a `null` value, which Lavalink doesn't support and will throw an error for.

player/seek: Remove mention of 'None' for seeking.

---

wavelink/pool.py

I just fixed a small typo (a missing `d`) in the docstring of `Node.get_playlist`

node: fix typo in Node.get_playlist docstring

---

wavelink/websocket.py

fixed #156 
After first track has been replaced with `Player.play(track)`, track_end event triggered after `Player.play` done. So, after first track replaced, `Player._source` is always None and `Player.is_playing()` always returns False.

player: fixed missing source after track replace (#156)

---

pyproject.toml
wavelink/__init__.py
wavelink/ext/spotify/__init__.py

Fixed a small type issue in SpotifyRequestError and renamed the SpotifyTrack.duration attribute to SpotifyTrack.length attribute to make it consistent with other types of Tracks

Fixed small type issue & make spotify track attr consistent with other tracks

---

wavelink/ext/spotify/__init__.py

Fixed the issue resulting from a KeyError when making SpotifyTracks from album links due to Spotify's album endpoint not providing album information per track. Also fixed the issue where tracks on albums would be turned into SpotifyTracks before intended. 
Spotify's album endpoint still does not provide any ISRC's for tracks so SpotifyTrack's isrc attribute can now be str or None.

Fixed SpotifyTrack creation from album source

---

wavelink/queue.py

```
Python 3.11.2
Wavelink==2.0.0b8
```
The simplest way to reproduce this is to call `player.queue.put_at_front(track)`
It looks like a copy-pasta bug.
**Traceback**
```
Traceback (most recent call last):
File "C:\Users\senpos\PycharmProjects\gigabot\venv\Lib\site-packages\discord\app_commands\commands.py", line 841, in _do_call
return await self._callback(self.binding, interaction, **params)  # type: ignore
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\senpos\PycharmProjects\gigabot\bot\cogs\music.py", line 46, in play
player.queue.put_at_front(track)
File "C:\Users\senpos\PycharmProjects\gigabot\venv\Lib\site-packages\wavelink\queue.py", line 205, in put_at_front
self.put_at_index(0, item)
File "C:\Users\senpos\PycharmProjects\gigabot\venv\Lib\site-packages\wa …
```

Fix Queue._insert attribute error

---

wavelink/ext/spotify/__init__.py

This also fixes the following pyright issue and makes the code shorter:
```
Cannot assign member "isrc" for type "SpotifyTrack"
  Expression of type "str | None" cannot be assigned to member "isrc" of class "SpotifyTrack"
    Type "str | None" cannot be assigned to type "str"
      Type "None" cannot be assigned to type "str" 

Use get for isrc instead of try except

---

wavelink/player.py

When using `Player.set_filter` with `seek=True`, the current track would be skipped immediately because an invalid position was passed to `Player.seek`.
`self.position` is already in milliseconds, so there is no need to multiply it by 1000

Fix Player.set_filter seeking

---

wavelink/tracks.py

YouTubePlaylist inherits Playable. Playable has a \_\_repr__ which YTP uses. That \_\_repr__ needs a `source`. YTP never gets a source set.
```py
File "C:\langs\Python310\lib\site-packages\wavelink\tracks.py", line 128, in __repr__
return f'Playable: source={self.source}, title={self.title}'
AttributeError: 'YouTubePlaylist' object has no attribute 'source'
```
This should fix it

fix: __repr__ on youtube playlists

---

docs/_static/styles/furo.css
docs/conf.py
docs/requirements.txt
pyproject.toml
wavelink/__init__.py
wavelink/websocket.py

Update some of the docs styling to be more visually appealing.
Added hoverxref to docs for referencing sphinx roles without having to click through to them. This also works between wavelink and discord.py/python docs.
Bump version.

Docs CSS and hoverxref update.

---

wavelink/ext/spotify/__init__.py

When requesting albums, the Spotify API only returns SimplifiedTrackObjects that do not contain all the track information received when requesting tracks or playlists. #197 attempted to resolved this by making the ISRC optional on SpotifyTracks. However, Wavelink uses the ISRC of SpotifyTracks in their fulfill function.  
```py
try:
tracks: list[cls] = await cls.search(f'"{self.isrc}"')
except wavelink.NoTracksError:
tracks: list[cls] = await cls.search(f'{self.name} - {self.artists[0]}')
```
In both #219 and my own observations these missing ISRC have resulted in the incorrect song to be repeatedly found. This PR would resolve the SimplifiedTrackObjects into full ones, preventing this issue, as well as end #209.
Additional it resolves the issue discussed in #221 without any breaking …

Spotify Extension Fixes (Album/ISRC and minor issues)

---

wavelink/ext/spotify/__init__.py

See #90
Added explicit attribute to `SpotifyTrack` class.
It is part of the Spotify `https://api.spotify.com/v1/tracks` response
Now you can just do:
```py
if track.explicit == True:
```

add explicit attribute to SpotifyTrack 

---

pyproject.toml
wavelink/backoff.py
wavelink/filters.py
wavelink/lfu.py
wavelink/node.py
wavelink/player.py
wavelink/queue.py
wavelink/tracks.py
wavelink/types/filters.py
wavelink/types/request.py
wavelink/types/state.py
wavelink/types/websocket.py

Ideally, this doesn't result in any change to the functionality; it's more about making the typing syntax consistent with python 3.10+ and ensuring pyright flags it accordingly if it isn't.

Clean up some typing syntax

---

docs/migrating.rst
docs/wavelink.rst
wavelink/player.py
wavelink/tracks.py
wavelink/types/request.py
wavelink/types/tracks.py
wavelink/utils.py

This adds extras to Playable for passing and accessing the `userData` field from Lavalink.
This PR implements a new class `ExtrasNamespace` which is just a small alteration of `types.SimpleNamespace`.

Add extras for userData in Lavalink

---

docs/migrating.rst
docs/wavelink.rst
wavelink/payloads.py
wavelink/websocket.py

This adds an `on_wavelink_extra_event` dispatched event for all unhandled or unknown events received via Lavalink. This only happens when a Plugin sends an event as all base Lavalink events are currently handled.

Add extra_event for unknown plugin events

---

docs/migrating.rst
docs/wavelink.rst
wavelink/node.py
wavelink/player.py
wavelink/websocket.py

This adds the `on_wavelink_inactive_player` event which triggers when a Player is considered inactive.
For now I have included a basic example, but in the future will add some more advanced recipes to the documentation.

Implementation of the inactive player event.

---

requirements.txt

yarl 1.9.2 provides wheels only for Python versions up to 3.11, making Wavelink installation on Python 3.12 harder than it should be on setups without build deps.
Changing the requirement to `yarl>=1.9.2` fixes this

Remove pinned dependency on yarl==1.9.2

---

wavelink/tracks.py

Current implementation is trying to add ExtrasNamespace to track object rather than Track.extras
This change sets the ExtrasNamespace correctly to Track.extras

Track.extras (userData) for Playlist

---

.gitignore
wavelink/player.py
wavelink/queue.py

Adds a new implementation of `wavelink.Queue`. Most of this design is reused from @Sachaa-Thanasius in #255
I have tested this pretty extensively both with and without a bot and everything seems to be behaving as it should.

Feature/queue redesign (New Queue implementation)

---

wavelink/player.py

Fix songs not repeating even though QueueMode.loop and AutoPlay.partial/AutoPlay.enabled are set.

Fix queue loop not repeating song after it's finished

---

wavelink/filters.py

Changed to use the properly typed keys
`lowPass` -> `low_pass`
`channelMix` -> `channel_mix`
Changes to be committed:
modified:   wavelink/filters.py

Fix & document Filters

---

wavelink/filters.py

Fix typos in filters doc string

Update comment filters

---

README.md
wavelink/node.py
wavelink/player.py
wavelink/tracks.py

Allows a `Node` to be passed to both `Playable.search` and `Pool.fetch_tracks` to search for the given query. If `None` is passed (Default) both of these methods act as they previously did.
This also adds:
Add the inactive_channel check to Player. The check dispatches the currently available wavelink_inactive_player event via Discord.py when a channel is deemed inactive.
An inactive channel is one where no real(non-bot) members are in the channel for a specified amount of played tracks. This differs from the current inactive_timeout which is a time based check on how long the player has not been playing, though they both work together.

Feature/playable node and Inactive Channel Check
