examples/playlist.py
wavelink/websocket.py

Only thing right now preventing 3.6 support as for as I know is `asyncio.create_task`. Not sure if there are other things.

Support Python 3.6

---

README.rst

Identified 'Music' as a proper cog to support the new d.py rewrite update.

Example file updated

---

examples/advanced/advanced.py
examples/basic.py
examples/playlist.py

Update examples to adhere to cog changes in discord.py

---

wavelink/player.py

The previous code worked as expected and should be reverted.

Revert changes to is_playing

---

wavelink/player.py

Get track's author the `info` dict

Added Track.author

---

setup.py
wavelink/__init__.py

Bump version to 0.3.02

---

wavelink/player.py

Instead of showing a small thumbnail, it would be great if we could show a bigger one.

Increase thumbnail size.

---

wavelink/player.py

The old one wasn't case insensitive.

Fix regex for YouTube video ID.

---

wavelink/node.py

Track identifier was not being encoded in /decodetrack

fix url encode

---

wavelink/player.py

Documentation change. Built and tested.

Add documentation for `Player.position`.

---

wavelink/player.py

There was a typo in the Track class description.

Fix typo Track class

---

wavelink/client.py

This PR adds session as  keyword argument

Add session as keyword argument to wavelink.Client

---

wavelink/player.py

Added a option to let users choose whether they want the player to self deafen or not.

Self deafen option.

---

wavelink/tracks.py

From [this commit](https://github.com/Pycord-Development/Pycord.Wavelink/commit/065fa414dab58b16ab71c87d940fe9f57d7f5350) on the Pycord Wavelink fork

Subclass YTM Track from YT Track

---

wavelink/__main__.py

Correct `could make directory` to read `couldn't make directory`.

Correct typo in __main__.py

---

wavelink/__init__.py
wavelink/backoff.py
wavelink/enums.py
wavelink/exceptions.py
wavelink/node.py
wavelink/payloads.py
wavelink/player.py
wavelink/queue.py
wavelink/tracks.py
wavelink/types/events.py
wavelink/types/request.py
wavelink/types/state.py
wavelink/types/track.py
wavelink/websocket.py

Begin work on updating types for 2.0

---

wavelink/ext/spotify/__init__.py
wavelink/player.py

This is so that the recommendations are guild specific.

Move _track_seeds attribute to player

---

wavelink/ext/spotify/__init__.py

Fixes the `"SearchableTrack" is not defined` error

FIx SearchableTrack TypeVar

---

.github/workflows/signoff.yaml

Automates check for PR authors having agreed to the last bullet point in the PR template. Copy of https://github.com/PythonistaGuild/.github/pull/1

Validate DCoF PR signoff

---

wavelink/player.py

This fixes a minor typo in the `set_filters` method docstring.

Fix typo in Player.set_filters

---

pyproject.toml
wavelink/__init__.py

Eviee py patch 1
